### PR TITLE
Missing dependency?

### PR DESCRIPTION
**Pull request by NikNikovsky**
I really am guessing here, not expecting this to be merged

### CODE REVIEW

**Comment by nulqwy** [comment]
the issue with libmagic only happens on windows (due to windows being very good™, it doesnt have `libmagic` binary),
so the actual change should have been adding
```
python-magic-bin; sys.platform == 'win32'
```

**Comment by nulqwy** [comment]
ALSO, `py` is a windows-only thing as well (due to, again, windows being very good™)

**Comment by NikNikovsky** [comment]
I will just add a new line then

**Comment by nulqwy** [comment]
> I will just add a new line then

hm?

**Comment by NikNikovsky** [comment]
that ok?

**Comment by nulqwy** [comment]
> that ok?

no, because `python3` works on windows as well, i was talking about the change you made `python -m venv venv` -> `py -m venv venv`

`py` is windows-only (and it was introduced due to crappiest handling of `PATH` in windows)

**Comment by NikNikovsky** [comment]
alright, that ok?

**Comment by nulqwy** [comment]
yeee

**Comment by eversiege** [comment]
TODO: write proper readme for backend, should consult DWC before starting work on documentation about backend

**Pull request merged**
